services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

 backend:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - backend_outputs:/app/outputs
    depends_on:
      - sqlserver

  frontend:
    build: ./src/frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  sql_data:
  backend_outputs:



